WebAppAss12/Models/CricketTeam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppAss12.Models
{
    public class CricketTeam
    {
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public int NOWC { get; set; }

        internal static void Add(CricketTeam team)
        {
            throw new NotImplementedException();
        }
    }
}

WebAppAss12/Controllers/CricketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppAss12.Models;

namespace WebAppAss12.Controllers
{
    public class CricketController : Controller
    {
        static List<CricketTeam> listCricketTeams = new List<CricketTeam>()
        {
           new CricketTeam() { TeamId =1,TeamName="india",NOWC=2},
           new CricketTeam() { TeamId =2,TeamName="Australia",NOWC=4},
           new CricketTeam() { TeamId =3,TeamName="Weat Indies",NOWC=2},
           new CricketTeam() { TeamId =4,TeamName="England",NOWC=1},
        };
        // GET: Cricket
        [HttpGet]
        public ActionResult create()
        {
            return View(new CricketTeam());
        }
        [HttpPost]
        public ActionResult Create(CricketTeam team)
        {
            if (ModelState.IsValid)
            {
                listCricketTeams.Add(team);
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult Index()
        {
            return View(listCricketTeams);
        }
       public ActionResult PAction()
       {
            return PartialView("PView");
       }

    }
}

WebAppAss12/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppAss12.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebAppAss12/Views/Cricket/Index.cshtml
@model IEnumerable<WebAppAss12.Models.CricketTeam>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NOWC)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TeamId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TeamName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NOWC)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

WebAppAss12/Views/Cricket/create.cshtml
@model WebAppAss12.Models.CricketTeam

@{
    ViewBag.Title = "create";
}

<h2>create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CricketTeam</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TeamId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOWC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOWC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOWC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List","index")
</div>

WebAppAss12/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebAppAss12/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebAppAss12/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h1>First Way</h1>
            @{ Html.RenderPartial("PView");}

        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
        </section>
    </div>
</main>

WebAppAss12/Views/Shared/PView.cshtml
<h1>Our Cricket Web</h1>
<img src="~/images/WhatsApp Image 2023-12-26 at 15.09.49_2ed97196.jpg"  height="150" width="150" class="img-responsive" style="border:2px solid red" />

WebAppAss12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cricket Info Web</title>
    <link href="OurStyle.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>Cricket Info Web</header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Cricket Info Web", "Home", "Cricket", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Cricket", "Index", "Cricket", new { area = "" }, new { @class = "nav-link" })</li>
                   </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            All Rights Reserved
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>